# Generated by Django 3.2.3 on 2021-05-24 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.IntegerField(choices=[(1, 'Free'), (2, 'Bronze'), (3, 'Gold'), (4, 'Platinum')], default=1)),
                ('pin', models.CharField(max_length=10)),
                ('duress_code', models.CharField(max_length=10)),
                ('in_emergency', models.BooleanField(default=False)),
                ('emergency_msg', models.CharField(default='I am in trouble and I need assistance. Please contact me ASAP.', max_length=4096)),
                ('continual_monitoring', models.BooleanField(default=False)),
                ('check_interval', models.IntegerField(default=240)),
                ('last_check_in', models.DateTimeField(blank=True, null=True)),
                ('checked_in_until', models.DateTimeField(blank=True, null=True)),
                ('emergency_started', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('sms_capable', models.BooleanField(default=True)),
                ('emergency_contact', models.BooleanField(default=True)),
                ('last_voice', models.DateTimeField(blank=True, null=True)),
                ('last_sms', models.DateTimeField(blank=True, null=True)),
                ('last_ack', models.DateTimeField(blank=True, null=True)),
                ('retry_interval', models.IntegerField(default=60)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
