# Generated by Django 3.2.3 on 2021-05-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='message_transcribe',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='message_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
